### ISSUE TITLE
programs needed on apollo2-dev and i5k-dev for content processing

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#120]
This issue documents installation of the programs needed on apollo2-dev and i5k-dev for content processing.

1. Apollo2-dev: A sysadmin will need to install the following scripts/programs on apollo2-dev in a location that a content processor (not sysadmin) can run them:
- Blat, faToTwoBit, wigToBigWig from here: http://hgdownload.soe.ucsc.edu/admin/exe/. 
- The samtools suite: http://www.htslib.org/
- It would be great if we could have a python virtualenv set up for general access where the following is installed: `pip install cwlref-runner`.
- Apollo/jbrowse scripts: These are under apollo_master/jbrowse/bin/ currently. They should be on apollo2-dev with the current apollo install now, but I can't find them since I don't have permissions
  - once these are accessible we'll have to see about the perl5/perl module access issues that we usually have. TBD.

2. i5k-dev: it would be great if a sysadmin could set up a python virtualenv set up for general access where the following is installed: `pip install cwlref-runner`.

**Comment by childers** [comment]
faToTwoBit is in /usr/local/bin/ but needs libpng 
```
./faToTwoBit: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

/usr/local/bin has the the files:
```
dev bin]$ ll
total 11160
-rwxr-xr-x. 1 root root 6225088 Aug  9 13:24 blat
-rwxr-xr-x. 1 root root 5198792 Aug  9 13:24 faToTwoBit
lrwxrwxrwx. 1 root root      36 Aug  9 13:23 yarn -> ../lib/node_modules/yarn/bin/yarn.js
lrwxrwxrwx. 1 root root      36 Aug  9 13:23 yarnpkg -> ../lib/node_modules/yarn/bin/yarn.js
```

As @mpoelchau mentioned, wigToBigWig can be installed as a precompiled binary fro the link above.

**Comment by g8tor** [comment]
The requested software is now availae on apollo2:
- blat -> /usr/local/bin/blat
- faToTwoBit -> /usr/local/bin/faToTwoBit
- wigToBigWig -> /usr/local/bin/wigToBigWig
- cwl-runner -> /usr/local/bin/cwl-runner
- cwltool -> /usr/local/bin/cwltool

The apollo_master directory has been synced from apollo-node1 to /app/data/WebApollo_deployment/apollo_master/ on apollo2-dev.

Finally, I have installed cwlref-runner in the virtual environment for both the i5k and i5k-training users. In order to use the cwl-runner and cwltool, members of either the i5k or i5k-training groups need only sudo to either. (sudo s -l i5k).

Closing this ticket.
