### ISSUE TITLE
Foreign key issue with migrated database

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#142]
@Ferrisx4 found out that there are a number of entries in the feature_relationship table that have no associated entry in the feature table. Abdullah thinks this is likely due to a bug in our Tripal2 database (remnant from migration from Tripal1) - foreign keys aren't specified in this table. In theory the T2-3 migration process should take care of this, but it looks like it doesn't. 

- go through all (?) migrated tables to make sure that a foreign key exists, but if not, add it and include this step in the migration documentation/process
- create tripal issue bringing up the fact that these foreign keys aren't checked/generated 
- identify and delete remnant entries in feature_relationship and other tables

**Comment by Ferrisx4** [comment]
https://github.com/tripal/tripal/issues/1098 Issue created on the Tripal repo

**Comment by Ferrisx4** [comment]
Discussion with Lacey on 13 October lead to two conclusions:
1. The migration process needs to be fixed within Tripal so that sites that are still upgrading from 1.2 to 1.3 upgrade properly (with all foreign key and other constraints).
2. For sites already upgraded, a script needs to be created that attempts to add any missing constraints. 

<hr> 

For the first task, we brainstormed briefly an approach that would be able to amend the current upgrade script with all of the required ALTER TABLE statements. As it stands, the current 1.2-1.3 upgrade SQL file is 50,000+ lines so this is not a trivial undertaking. This SQL file seems to have been borrowed by collating scripts from the [GMOD/Chado](https://github.com/gmod/chado) repository. 

For the second task, by comparing fresh Chado 1.3 schema dump with a Chado 1.3 schema dump that had been upgraded from 1.2, an SQL file was generated with the differences filtered down to only those that are related to table constraints. This process seems flawed because when the sql file was run, the database indicated that a lot of the constraints were already in place, so it skipped them. Otherwise, the sql file was successful - tables such as feature_relationship now have their foreign keys set.

**Comment by mpoelchau** [comment]
@Ferrisx4 what's the status on this issue?

**Comment by mpoelchau** [comment]
Closing, this does not affect our migration and is reported in https://github.com/tripal/tripal/issues/1098.
